### ISSUE TITLE
use ID3 'Track' number for ordering, instead of file creation time

### ISSUE THREAD

**Issue by korovkin** [nerab/dropcaster#12]
why did you decide to use file creation time for ordering? 

can you please add an option to order by id3 / filename  ?

**Comment by nerab** [comment]
Thanks for the comment. Could you please elaborate on why this is needed? 

Why shouldn't the latest episode be first in the feed? Or do you see cases where the latest episode doesn't have a time stamp that is the latest among all episode files?

Also, I believe most podcatchers order by the date that is written in the feed, so the order of entries in the feed doesn't matter that much anyway.

**Comment by korovkin** [comment]
i use dropcaster to convert a bunch of my audiobooks to podcasts that i use myself. 
something like that: 
http://podiobooks.com/

in order to create such pod-audiobook-casts i need to control the order of the files. 

i hacked the code a bit, and not adding <itunes:order> tag based on the files specified from the command line. skipping the sort. that works for me.

**Comment by nerab** [comment]
Dropcaster actually uses the file _modification_ time in the feed:

    File.new('episode.mp3').mtime

In order to mark `episode.mp3` as the latest, it should be enough to execute `touch episode.mp3` (assuming you are on a UNIX-like system, like Linux or OSX).

Would that work for you?

**Comment by korovkin** [comment]
I noticed that 

It doesn't work since pubDate is captured in seconds 

So I guess I should "sleep 2" between the touches... Which sucks :) 



sent from a 📞

**Comment by nerab** [comment]
That could work, but I agree it's not ideal.

**Comment by fadookie** [comment]
I have the exact same use case (creating private podcast/audiobook feed.)

It would be great if you could set sorting algorithm in the `.yml` file.

However in the meantime I think I have come up with a more performant method of changing mod-time as suggested above without having to sleep, as `touch` allows an absolute time to be passed. This bash 4 script sorts m4a files in reverse lexical order and sets absolute access/mod times relative to the beginning of the year. It should work fine if you don't care about the actual pubDate. It will overflow at 1,440 files but should be easy to modify to accommodate more if necessary.

```bash
#!/usr/bin/env bash
set -o errexit
set -o nounset
shopt -s globstar

FILES=(**/*.m4a)
HOUR_COUNTER=1
MINUTE_COUNTER=0
for ((i=${#FILES[@]}-1; i>=0; i--)); do # Loop backwards
    HOUR=$(printf "%02d" "$HOUR_COUNTER")
    MINUTE=$(printf "%02d" "$MINUTE_COUNTER")
    set -x
    touch -t "0101${HOUR}${MINUTE}" "${FILES[$i]}"
    set +x
    MINUTE_COUNTER=$((MINUTE_COUNTER + 1))
    if (( MINUTE_COUNTER > 59)); then
        MINUTE_COUNTER=0
        HOUR_COUNTER=$((HOUR_COUNTER + 1))
    fi
done
```
