### ISSUE TITLE
Handle difference cases for .MP3

### ISSUE THREAD

**Issue by hammady** [nerab/dropcaster#14]
If the files end with .mp3 but in different cases: MP3, Mp3 or mP3 they are not included in the output.

**Comment by nerab** [comment]
Thanks for the report. There is certainly an expectation to have lowercase file extensions. What software produces the other variants? Or is it your personal preference and you rename `mp3` to one of the variants on purpose?

**Comment by hammady** [comment]
I encountered this problem when exporting from iTunes on Mac. Maybe the original files have .MP3, not sure if iTunes preserves case.

**Comment by stephenwade** [comment]
Fixed in 11ff76bc712a7a7693e92cc162fa3b58ce332732.
