### ISSUE TITLE
Multiple errors when submitting to iTunes Podcasts Connect

### ISSUE THREAD

**Issue by orschiro** [nerab/dropcaster#17]
Dear @nerab, 

Thanks so much for your great work on this tool!

I created my `index.rss` based on the suggested `channel.yml` file. 

However, when submitting my podcast, I run into the following errors. 

How to resolve these?

Thanks,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/19411025/ab15cb2c-92f9-11e6-8ff3-9b512a5e88b8.png)

**Comment by nerab** [comment]
Thanks for the report. Was it solved with #16 already?

**Comment by orschiro** [comment]
Thanks, Nicholas!

How can I update dropcaster to try the merged branch?

**Comment by nerab** [comment]
* Clone the repo
* `bundle`
* `bundle exec bin/dropcaster`

I just realize that we should have some development instructions. I will add them separately.

**Comment by hammady** [comment]
I don't think #16 solves this issue. It only makes it compatible with Podcasts app but not through the iTunes server. I may work on this if i have time.

**Comment by orschiro** [comment]
I really appreciate your help! Please let me know if I can somehow help as well in solving this.

**Comment by nerab** [comment]
This may turn out to be a huge bummer - [it looks like Dropbox does not support byte range requests](https://theaudacitytopodcast.com/can-you-host-your-podcast-with-dropbox/).

**Comment by orschiro** [comment]
What does this mean?

**Comment by hammady** [comment]
@orschiro it means that Dropbox is not the suitable hosting place for podcasts. I agree on that, but this does not make dropcaster any bad as it is still useful for any other hosting. I personally host my podcasts on S3 and it works like charm.

**Comment by orschiro** [comment]
How easy is the workflow with S3?

**Comment by hammady** [comment]
@orschiro S3 requires a bit of setup at first and generally it is [not free](https://aws.amazon.com/s3/pricing/). After that, you can upload by drag and drop (or use their API of course through any client). Alternatively, just use any web hosting like hostgator, godaddy, digitalocean, ... which are as simple as FTP.

**Comment by orschiro** [comment]
I like the idea to drag and drop.

Is there any tutorial that I can follow to set-up S3?

**Comment by hammady** [comment]
Check the [S3 official tutorial](http://docs.aws.amazon.com/AmazonS3/latest/gsg/GetStartedWithS3.html).
Warning: AWS is meant for developers to integrate the services with their apps, other hosting options are meant for end-users, and they also have drag and drop.

**Comment by orschiro** [comment]
Thanks!

**Comment by nerab** [comment]
Browsing the Dropbox pages, it looks like they [removed the public folder feature long ago](https://www.dropbox.com/help/16). With that, relative links from `index.rss` to `mp3` files no longer work (at least not for accounts created after 2012).

I think it's time to find a new meaning of "drop" in "dropcaster" and remove all references to Dropbox.

**Comment by orschiro** [comment]
So, how does JustCast work?

https://justcast.herokuapp.com/

**Comment by vitorgalvao** [comment]
@nerab If you’re a paid user you can still make a public folder ([documentation](https://www.dropbox.com/help/16)).

@orschiro Don’t quote me on this, but I think Justcast uses the Dropbox API. That means it’s a properly registered app that has access to official features. Dropcaster, in comparison, works by cleverly using a feature that does not require access to the API (and has since been phased out).

**Comment by orschiro** [comment]
Thanks, Vitor!

**Comment by nerab** [comment]
Dropbox took away public folders for everyone :-(
