### ISSUE TITLE
enclosure url results in "404 cannot find" when podcatcher tries to download mp3 file

### ISSUE THREAD

**Issue by BartMulder** [nerab/dropcaster#19]
Hi @nerab,

Great tool, just what I was looking for! 

I've got one problem: When my podcatcher (BeyondPod) tries to download the mp3 files, it basically receives an html file saying "404 cannot find what you are looking for". When I replace the enclosure urls in index.rss with public links generated by Dropbox (like you do to share index.rss), it does work however. 
Am I doing something wrong with Dropbox so that the dropcaster generated enclosure urls don't work? Or did Dropbox change something?

I've attached the html file (as txt), but I guess you get what I mean.
[podcast123.mp3.html.txt](https://github.com/nerab/dropcaster/files/573354/podcast123.mp3.html.txt)

Thanks!
Bart

**Comment by vitorgalvao** [comment]
Can you give me:

+ The full path to the directory where you have the files.
+ The contents of you `channel.yml`.
+ The contents of your feed (as opposed to the HTML).
+ The exact command you used for generating the HTML/feed.

**Comment by BartMulder** [comment]
Sure thing:

- C:\Users\digit\Dropbox\Public> (I'm on Windows)
- [channel.yml.txt](https://github.com/nerab/dropcaster/files/573385/channel.yml.txt)
- The feed contains 2 mp3 files (downloading them and playing them works fine when I replace the enclosure urls with links generated by Dropbox). Does that answer your question?
- dropcaster > index.rss (Like per your instructions. Everyting fine and the generated index.rss looks good)

This is an example of an index.rss (generated by dropcaster) that doesn't work: 
[index.rss.txt](https://github.com/nerab/dropcaster/files/573387/index.rss.txt)

This is an example of an index.rss - modified by me with Dropbox generated links -  that works:
[index.rss.OK.txt](https://github.com/nerab/dropcaster/files/573389/index.rss.OK.txt)

Thanks!
Bart

**Comment by vitorgalvao** [comment]
The problem is in your `channel.yml`. `dropcatcher` will use the `url` as the base directory for your files, so change it from

```yml
:url: 'https://www.dropbox.com/sh/81w4ifar6qbevht/AAANsWqjMIWDRyF1vJBc1S2Ua?dl=0/index.html'
```

to

```yml
:url: 'https://dl.dropboxusercontent.com/u/28147526'
```

and it should work.

**Comment by BartMulder** [comment]
Of course! My bad. Thanks man, you're awesome!
