### ISSUE TITLE
Order of feed

### ISSUE THREAD

**Issue by sacc91** [nerab/dropcaster#20]
I've had problems generating feeds in order. I've tried a few different ways and the thing that seems to work is naming the files sequentially with a two digit number (01, 02, etc.) but the feeds still won't load in order for Overcast.
![screenshot](https://cloud.githubusercontent.com/assets/255272/22916138/2f81d700-f242-11e6-8815-36637415b027.jpg)

**Comment by sacc91** [comment]
I think I found the cause of the issue. If a file has the character '&' and I suspect other special characters too, the xml file is not generated escaping those characters correctly, which screws up feed parsing in a lot of applications. iTunes won't even parse it at all unless you correct every '&'  to  &amp; in the rss file manually.

This image is a comparison of the dropcaster output versus a normal podcast xml file.
<img width="1313" alt="screenshot 2017-02-14 00 57 11" src="https://cloud.githubusercontent.com/assets/255272/22918599/a47a5e98-f250-11e6-8286-25e4134df50a.png">

**Comment by nerab** [comment]
Interesting; thanks for the report. Could you contribute a test case that reproduces the issue?

**Comment by sacc91** [comment]
Like this? https://dl.dropboxusercontent.com/u/1375875/misc/test/index2.rss
https://dl.dropboxusercontent.com/u/1375875/misc/test/channel.yml

<img width="303" alt="screenshot 2017-02-19 12 21 10" src="https://cloud.githubusercontent.com/assets/255272/23104997/eab61158-f69d-11e6-9c08-574ddd8161f4.png">

**Comment by stephenwade** [comment]
This should be renamed something like "Dropcaster generates invalid XML when filenames have special characters".
