### ISSUE TITLE
Encoding issue 

### ISSUE THREAD

**Issue by darkzbaron** [nerab/dropcaster#22]
Hi there,

I am unable to process files with unicode names when running in command line mode:

This works `dropcaster > index.rss`

This does not `dropcaster somefilewithunicode*.mp3` and returns 
`ERROR: Invalid argument @ rb_sysopen - somefilewithunicode1.mp4`

Thanks,Jonathan
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32] - Win10

**Comment by nerab** [comment]
Can you please provide a concrete example for a filename where it fails as described?
