### ISSUE TITLE
Explain in ReadMe which ID3 tags to use

### ISSUE THREAD

**Issue by dkhgh** [nerab/dropcaster#79]
I'd like to be able to find in the Readme of this repo which ID3 tags dropcaster uses to generate XML tags for the RSS file. 

For example, for my podcast, I want to set these tags for each item but I don't know which ID3 tags to use: 

```xml
<description></description>
<itunes:summary></itunes:summary>
<itunes:subtitle></itunes:subtitle>
```

**Comment by stephenwade** [comment]
`<description>` is only at the channel level, not the item level. That is set by the channel YML file.

In an item, `<itunes:summary>` and `<itunes:subtitle>` are set by the "Subtitle/Description refinement" ID3 tag (TT3, or TIT3 as soon as #81 is merged).

**Comment by nerab** [comment]
@dkhgh #81 was indeed merged. Does it solve your issue? If so, could you contribute a patch to the README, please?

**Comment by nerab** [comment]
Please re-open if the problem still persists.
